### ISSUE TITLE
Continued Development

### ISSUE THREAD

**Issue by Dylan-M** [gphoto/gtkam#3]
It would be nice to see development of gtkam continued. I've used it for years as the best photo import tool on Linux. It is far superior to others in my opinion, and (due to the gphoto backhend) handles cameras and SD cards that the other programs choke on. Please bring this software back to life.

**Comment by hfiguiere** [comment]
You can submit patches. Development goes as far as the volunteers go.

**Comment by Dylan-M** [comment]
Sadly well aware of that. However, I don't have the needed skills to work on this project. For this one, I'm just a consumer. I mostly wanted people to be aware that there is definitely still interest in this project. I'm not along in my feelings of gtkam over things like digiKam.

**Comment by pinkavaj** [comment]
Is there any specific feature missing, something specific to improve, bugs to resolve or something (like for example port to GTK3)? Is there any use case from user point of view wich GtKam does not handle well? If You spell it out, meybe someone will do it.

**Comment by Dylan-M** [comment]
While GTK3 would be amazing, I'd rather, for now, just see the compile issues and such fixed. As such, I posted a report about those.

**Comment by hfiguiere** [comment]
Please file individual bugs for individual issues.

**Comment by hfiguiere** [comment]
Marcus just released a 1.0
