### ISSUE TITLE
Unable to compile on Fedora 23

### ISSUE THREAD

**Issue by Dylan-M** [gphoto/gtkam#4]
I was unable to compile the base code on Fedora 23 as is due to many library issues.

However, by using the patches from this Arch snapshot I was able to get it to compile.
https://aur.archlinux.org/cgit/aur.git/snapshot/gtkam.tar.gz

I haven't yet looked at rebuilding the Fedora RPM from the last source RPM Fedora released, but I have to assume it has similar patching done.

Note: These patches are against the last released version on Sourceforge.

I can attempt a recompile later in a different folder to reproduce the errors and dump some logs into attachments.

You can also read about the issues on the Arch packages tracker for gtkam:
https://aur.archlinux.org/packages/gtkam/?comments=all

One final note, even with the patches I couldn't get a successful 'make install', but I could successfully compile and run the binary locally.

**Comment by hfiguiere** [comment]
gtkam isn't even in Fedora 24...

**Comment by hfiguiere** [comment]
But git master builds and run on Fedora 24. No patch needed.

**Comment by hfiguiere** [comment]
(and make install works too)

**Comment by msmeissn** [comment]
I need to cut a release though

**Comment by msmeissn** [comment]
i rolled a 1.0 release of gtkam. 

if that does not build, please speak up

**Comment by Dylan-M** [comment]
You threw me off putting the release on SF instead of here on GH, but I found it ;)

Attached is the build failure from 0.2.0 just because I said I would.
[gtkam0.2.0.txt](https://github.com/gphoto/gtkam/files/286389/gtkam0.2.0.txt)

However, the new v1 release compiles cleanly, and make install works. So thank you.
